# ================
# DNA Segmentation
# ================

dna:

  # Smooth

  BILATERAL_SIGMA_COLOR: 0.1
  BILATERAL_SIGMA_SPATIAL: 3

  # Threshold

  THRESHOLD_FACTOR: 0.5

  # Sparse Segmentation

  LOG_SPARSE:
    MIN_SIG: 5 
    MAX_SIG: 8
    NUM_SIG: 4
    THRESH: 0.1
    OVERLAP: 0.3

  WATERSHED_CONN: [[0,1,0],[1,1,1],[0,1,0]]
  WATERSHED_COMPACTNESS: 1000
  WATERSHED_MIN_SZ: 30

  # Clump Detection

  SEG_SINGLE_MIN_SZ: 300 
  SEG_SINGLE_MAX_SZ: 400

  SEG_CLUMP_SOLIDITY: 0.75

  SEG_CLOSE_HOLES: 3

  # Dense Segmentation

  LOG_DENSE:
    MIN_SIG: 2
    MAX_SIG: 6
    NUM_SIG: 5
    THRESH: 0.15
    OVERLAP: 0.01
  
# ================
# EdU Segmentation
# ================

edu:

  # Smooth

  BILATERAL_SIGMA_COLOR: 0.1
  BILATERAL_SIGMA_SPATIAL: 3

  # Threshold

  THRESHOLD_FACTOR: 0.5

  # Sparse Segmentation

  LOG_SPARSE:
    MIN_SIG: 5 
    MAX_SIG: 7
    NUM_SIG: 3
    THRESH: 0.1
    OVERLAP: 0.3

  WATERSHED_CONN: [[0,1,0],[1,1,1],[0,1,0]]
  WATERSHED_COMPACTNESS: 1000
  WATERSHED_MIN_SZ: 30

  # Clump Detection

  SEG_SINGLE_MIN_SZ: 300 
  SEG_SINGLE_MAX_SZ: 400

  SEG_CLUMP_SOLIDITY: 0.8

  SEG_CLOSE_HOLES: 3

  # Dense Segmentation

  LOG_DENSE:
    MIN_SIG: 2
    MAX_SIG: 5
    NUM_SIG: 4
    THRESH: 0.1
    OVERLAP: 0.01

# ===================
# Goblet Segmentation
# ===================

goblet:

  # Smooth
  MEDIAN_FILTER_SZ: 3

  # Threshold

  THRESHOLD_FACTOR: 1

  # Segment

  LOG_BLOB: 
    MIN_SIG: 5
    MAX_SIG: 12
    NUM_SIG: 7
    THRESH: 0.01
    OVERLAP: 0.2

  WATERSHED_CONN: [[0,1,0],[1,1,1],[0,1,0]]
  WATERSHED_MIN_SZ: 50
  WATERSHED_COMPACTNESS: 1000

# ========================
# Stem Segmentation
# ========================

crypt:

  # Crypt Threshold

  DNA_FACTOR: 0.3
  THRESH: 0.1

  # Crypt Processing
  
  MORPH_CLOSING_SZ: 8
  MORPH_OPENING_SZ: 4
  MIN_SZ: 2000

stem:

  # Identify Stem 
  
  PARTIAL_RATIO: 1.5