# ==============================================================================
# This config file defines setting parameters
# ==============================================================================

paths:
  result: 'output/{object_type:s}_pipeline_result.png'
  segmentation: 'output/{object_type:s}_segmentation.tiff'
  overlay: 'output/{object_type:s}_overlay.png'

max_px_val: 4095
